---

- name: Ensure that wrapper for {{ flatpak.package }} is in {{ lookup('env','HOME') }}/.local/bin/
  ansible.builtin.copy:
    content: "{{ lookup('vars', 'user' ) | replace('/usr/bin/', '') }}"
    dest: "{{ lookup('env','HOME') }}/.local/bin/{{ command }}"
    mode: "a+x"
  vars:
    #system: "/var/lib/flatpak/app/{{ flatpak.package }}/current/active/export/bin/{{ flatpak.package }}"
    user: "{{ lookup('env','HOME') }}/.local/share/flatpak/app/{{ flatpak.package }}/current/active/export/bin/{{ flatpak.package }}"
  loop: "{{ flatpak.commands | default([]) }}"
  loop_control:
    loop_var: command