---
- name: Ensure that common packages are installed
  become: yes
  apt:
      state: present
      name:
        # all of the useful terminal commands
        # should be pre-installed but it's here just to make sure
        - coreutils

        # password manager
        # can also integrate with SSH agent
        - keepassxc

        # so that we can use `add-apt-repository`
        - software-properties-common
        - dirmngr
        - apt-transport-https
        - lsb-release
        - ca-certificates

        # other stuff
        - curl
        - fzf

# ---------------------------------------------------------------------
# create a folder to put my dotfiles and scripts

- name: Ensure that the .config/dotfiles directory exists
  file:
      path: "{{ dotfiles }}"
      state: directory

- name: Ensure that the .config/dotfiles/scripts directory exists
  file:
      path: "{{ dotfiles }}/scripts"
      state: directory

- name: Ensure that the .config/dotfiles/scripts directory exists
  file:
      path: "{{ dotfiles }}/cheatsheets"
      state: directory

# ---------------------------------------------------------------------
# put the script for installing updates in the right place

- name: Ensure that .local/bin directory exists
  file:
      path: "{{ local_bin }}"
      state: directory

- name: Ensure that the check-for-updates is in the .local/bin
  copy:
      src: check-for-updates
      dest: "{{ local_bin }}/check-for-updates"

- name: Ensure that the check-for-updates script is executable
  file:
      path: "{{ local_bin }}/check-for-updates"
      mode: u=rx

# ---------------------------------------------------------------------
# put the email generator in the right place

- name: Ensure that the generate-email script is in the .local/bin
  copy:
      src: generate-email
      dest: "{{ local_bin }}/generate-email"

- name: Ensure that the generate-email script is executable
  file:
      path: "{{ local_bin }}/generate-email"
      mode: u=rx
