# the 'install' field is used when the name of the package that you're
# installing is different to the name/URL that you use to install it
pipx_apps:
  - name: poetry
  - name: ranger-fm
  - name: yt-dlp
    dependencies:
      - secretstorage
  - name: browserexport
  - name: pretty-history
  - name: toolbox-export
    install: git+https://github.com/apatel762/toolbox-export.git
  - name: cite
    install: git+https://github.com/apatel762/cite.git

  # these two are needed to build and install the cloze overlapper
  # Anki add-on (https://github.com/glutanimate/cloze-overlapper)
  - name: aab
  - name: pyqt5