---
- name: Set up local workstation
  hosts: local
  roles:
    - role: workstation
    - role: terminal
    - role: vim
    - role: ssh
    - role: nix-stuff
    # clean this up later
    - role: yt-dlp
    - role: cheatsheets