---

- name: Ensure that the Applications folder exists
  ansible.builtin.file:
    path: "{{ standalone_applications_folder }}"
    state: directory

- name: Ensure that all standalone apps are present in the Applications folder
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ standalone_applications_folder }}/{{ item.file_name }}"
    checksum: "{{ item.checksum }}"
    mode: "u=rwx,g=r,o=r"
  loop: "{{ standalone_applications }}"
